// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmzmzjwa9CvHtKEApPbQ46d4tkE8JEkPc',
    appId: '1:457230198022:web:995141a9191bfc841f2a87',
    messagingSenderId: '457230198022',
    projectId: 'glowza-326ca',
    authDomain: 'glowza-326ca.firebaseapp.com',
    storageBucket: 'glowza-326ca.firebasestorage.app',
    measurementId: 'G-V9PP45VKZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUoDl6CQ38WFoPHQKkFIOY8ZfE7erFe5Y',
    appId: '1:457230198022:android:00de5e280a9c44f01f2a87',
    messagingSenderId: '457230198022',
    projectId: 'glowza-326ca',
    storageBucket: 'glowza-326ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGX269rWiv5XqvMrVXxOYyxcG2xnU1dhI',
    appId: '1:457230198022:ios:7c558ccdf6e0e9341f2a87',
    messagingSenderId: '457230198022',
    projectId: 'glowza-326ca',
    storageBucket: 'glowza-326ca.firebasestorage.app',
    iosBundleId: 'com.example.glowza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGX269rWiv5XqvMrVXxOYyxcG2xnU1dhI',
    appId: '1:457230198022:ios:7c558ccdf6e0e9341f2a87',
    messagingSenderId: '457230198022',
    projectId: 'glowza-326ca',
    storageBucket: 'glowza-326ca.firebasestorage.app',
    iosBundleId: 'com.example.glowza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmzmzjwa9CvHtKEApPbQ46d4tkE8JEkPc',
    appId: '1:457230198022:web:846bc2df164327221f2a87',
    messagingSenderId: '457230198022',
    projectId: 'glowza-326ca',
    authDomain: 'glowza-326ca.firebaseapp.com',
    storageBucket: 'glowza-326ca.firebasestorage.app',
    measurementId: 'G-2MJZKCVBQZ',
  );
}
